services:
  evrinoma.cert.constraint.property.cert.title:
    class: Evrinoma\CertBundle\Constraint\Property\Cert\Title

  evrinoma.cert.constraint.property.cert.active:
    class: Evrinoma\CertBundle\Constraint\Property\Cert\Active

  evrinoma.cert.constraint.property.cert.position:
    class: Evrinoma\CertBundle\Constraint\Property\Cert\Position


